# Generated by Django 3.2.14 on 2023-03-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_review_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=100, null=True)),
                ('hourTime', models.IntegerField()),
                ('minuteTime', models.IntegerField()),
                ('age_rating', models.CharField(choices=[('G', 'General Audience'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movi'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
