# Generated by Django 3.0 on 2022-03-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220317_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
