# Generated by Django 3.2.14 on 2023-03-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230329_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movi',
            new_name='Movie',
        ),
    ]
