# Generated by Django 3.2.14 on 2023-03-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=500, null=True)),
                ('hourTime', models.IntegerField()),
                ('minuteTime', models.IntegerField()),
                ('age_rating', models.CharField(choices=[('G', 'General Audience'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5, null=True)),
                ('cast', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5, null=True),
        ),
    ]
