# Generated by Django 3.2.14 on 2023-03-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230329_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'R'), ('NC-17', 'Adults Only')], max_length=5, null=True),
        ),
    ]
