# Generated by Django 3.2.14 on 2023-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('12:00', '12:00 PM'), ('15:00', '3:00 PM'), ('18:00', '6:00 PM')], max_length=5),
        ),
    ]
