# Generated by Django 3.2.14 on 2023-04-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='theater',
            field=models.CharField(choices=[('PREMIERE LUX Cine 10', 'PREMIERE LUX Cine 10'), ('Cinema 1 & 2', 'Cinema 1 & 2'), ('Cinemark Town Centre Cinema 6', 'Cinemark Town Centre Cinema 6'), ('Cinemark', 'Cinemark'), ('PREMIERE LUX 16 IMAX', 'PREMIERE LUX 16 IMAX')], max_length=50),
        ),
    ]
