# Generated by Django 3.2.14 on 2023-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='encrypted_card_cvv',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='encrypted_card_number',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_cvv',
            field=models.IntegerField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_expiry',
            field=models.IntegerField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.IntegerField(blank=True, max_length=16),
        ),
    ]
