# Generated by Django 3.2.14 on 2023-04-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20230401_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_cvv',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_expiry',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
