# Generated by Django 3.2.14 on 2023-04-16 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20230401_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardNumberr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('card_number', models.IntegerField(max_length=16)),
                ('card_expiry', models.DateField(max_length=16)),
                ('card_cvv', models.IntegerField(max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
