# Generated by Django 3.0 on 2022-02-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220129_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_picture',
            field=models.ImageField(blank=True, default='bg_image.png', null=True, upload_to='img/%y'),
        ),
    ]
