# Generated by Django 3.0 on 2022-02-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_banner_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_picture',
            field=models.ImageField(blank=True, default='bg_image.jpg', null=True, upload_to='img/%y'),
        ),
    ]
