# Generated by Django 3.0 on 2022-02-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220215_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_picture',
            field=models.ImageField(blank=True, default='bg_image.png', null=True, upload_to='img/%y'),
        ),
    ]
