# Generated by Django 3.0 on 2022-02-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220215_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='artiste',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='time_length',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='title',
        ),
        migrations.AlterField(
            model_name='uploads',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
