# Generated by Django 3.0 on 2022-02-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220215_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=models.FileField(null=True, upload_to='img/%y'),
        ),
    ]
